name: Gradle Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'temurin'
          cache: 'gradle'

      - name: Build with Gradle
        uses: nick-invision/retry@v3
        with:
          timeout_minutes: 5
          max_attempts: 2
          command: gradle clean build
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: UnSignedVelocity
          path: build/libs/UnSignedVelocity-*.jar